"""Server-generated evaluator harness — plan item 2.5 (AF2 §4.1).

**Every field failure lived in the column the agent hand-wrote.** Polarity
inverted, latency gates applied at the wrong scope, domains never joined — all of
it in a file the mission authored from scratch, every time, while the parts that
are identical across every mission were re-derived by hand alongside them.

The split: the SERVER owns the harness — split loading, the domain join, the
count assertion, gate application, the trivial-predictor floor and the stdout
protocol — and the mission owns exactly one function::

    def score(pred, gt) -> dict[str, float]

Small, mission-specific, testable in isolation, and the only thing an agent
writes. Novel objectives stay fully expressible: F-measure, DRD and anything not
yet invented live in that function.

**Determinism is the point, not a nicety.** The output is a pure function of
`GoalContract` + `EvalSuite` + the frozen index, so the server can regenerate it
and byte-compare. That turns the seal from an assertion into CUSTODY — RC1's fix
falls out rather than needing separate hardening, which is the same move item 2.7
makes for the file itself.

**Known limit, stated rather than discovered.** A metric that must see raw
images (perceptual quality) or that is not decomposable per item (corpus-level
calibration, ranking over the whole split) does not fit `score(pred, gt)` and
needs an escape hatch. That is a real constraint of this boundary and is not
worked around here.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

SCORE_PLUGIN_FILENAME = "score_plugin.py"

#: Bumped when the emitted harness changes shape. A regenerated evaluator that
#: does not byte-match its seal is either tampering or a version skew, and the
#: two must be distinguishable — otherwise every upgrade looks like an attack.
HARNESS_VERSION = 1

_PLUGIN_TEMPLATE = '''"""score(pred, gt) — THE ONLY FILE THIS MISSION WRITES.

Everything else in the evaluator is generated by `evor_scaffold_evaluator` from
the goal contract: split loading, the domain join, the count assertion, gate
application, the trivial-predictor floor and the stdout protocol. Those are
identical across missions and were the source of every field failure when they
were hand-written.

Return a dict of metric name -> float. The harness handles aggregation,
per-domain grouping, and gates.

`pred` and `gt` are bytes as read from disk. Interpret them however this
mission's data requires.

POLARITY IS DECLARED, NOT ASSUMED: the contract states `label_semantics`
({label_semantics!r}), and the harness passes it in so this function never has to
guess which pixel value means ink. Guessing is what r1 and r2 both got wrong.
"""

from __future__ import annotations


def score(pred: bytes, gt: bytes, *, label_semantics: str = {label_semantics!r}) -> dict[str, float]:
    raise NotImplementedError(
        "write this mission's metric here — the harness around it is generated"
    )
'''


def _harness_source(
    *,
    contract: dict[str, Any],
    frozen_split: dict[str, Any],
    eval_version: str,
) -> str:
    """The generated harness. A pure function of its declared inputs."""
    metric_names = sorted(
        str(spec.get("metric_name"))
        for spec in (contract.get("metric_specs") or [])
        if spec.get("metric_name")
    )
    constraints = [
        {
            "metric": str(c.get("metric")),
            "op": str(c.get("op")),
            "threshold": float(c.get("threshold")),
            "scope": str(c.get("scope", "all")),
            "purpose": str(c.get("purpose", "floor")),
        }
        for spec in (contract.get("metric_specs") or [])
        for c in (spec.get("constraints") or [])
    ]
    per_sample_domains = frozen_split.get("per_sample_domains") or {}
    expected_count = int(frozen_split.get("item_count") or 0)

    return f'''#!/usr/bin/env python3
"""GENERATED by evor.scaffold_evaluator — DO NOT EDIT.

Regenerate with `evor_scaffold_evaluator`. This file is a pure function of the
goal contract, the eval suite and the frozen index, so the server can rebuild it
and byte-compare — which is what makes the seal CUSTODY rather than an assertion
(item 2.5 / RC1).

Editing it by hand breaks that property silently: the seal will still verify the
bytes you left, and the anchor will describe a file nobody can reproduce.

harness_version: {HARNESS_VERSION}
eval_version:    {eval_version}
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # __file__-anchored (R-15)

from {Path(SCORE_PLUGIN_FILENAME).stem} import score

LABEL_SEMANTICS = {contract.get("label_semantics", "unspecified")!r}
EXPECTED_ITEM_COUNT = {expected_count}
PER_SAMPLE_DOMAINS = {json.dumps(per_sample_domains, sort_keys=True)}
CONSTRAINTS = {json.dumps(constraints, sort_keys=True)}
FITNESS_MODE = {contract.get("fitness_mode", "aggregate")!r}
METRICS = {json.dumps(metric_names)}


def _load_split(split_dir: Path) -> dict[str, bytes]:
    """Load the frozen split. Count is ASSERTED, not assumed."""
    items = {{p.name: p.read_bytes() for p in sorted(split_dir.iterdir()) if p.is_file()}}
    if EXPECTED_ITEM_COUNT and len(items) != EXPECTED_ITEM_COUNT:
        # AF1: a freeze that captured 5 metadata files reported success, and
        # every fitness number in the run was computed against them.
        raise SystemExit(
            f"eval split has {{len(items)}} items, expected {{EXPECTED_ITEM_COUNT}}. "
            "Refusing to score against a split that is not the one that was frozen."
        )
    return items


def _aggregate(per_item: dict[str, dict[str, float]]) -> dict[str, float]:
    """Aggregate per-item scores, joining domains where the split declares them."""
    if not per_item:
        return {{}}
    out: dict[str, float] = {{}}
    # EVERY metric the plugin returned, not only the declared primaries. A
    # `MetricConstraint` exists to guard a SECONDARY metric — precision floors
    # against recall-gaming are the canonical case — so aggregating only declared
    # names silently drops the gate that matters most.
    for metric in sorted({{m for v in per_item.values() for m in v}} | set(METRICS)):
        values = [v[metric] for v in per_item.values() if metric in v]
        if not values:
            continue
        if FITNESS_MODE == "worst-domain" and PER_SAMPLE_DOMAINS:
            by_domain: dict[str, list[float]] = {{}}
            for item_id, metrics in per_item.items():
                if metric in metrics:
                    by_domain.setdefault(PER_SAMPLE_DOMAINS.get(item_id, "_"), []).append(metrics[metric])
            out[metric] = min(sum(v) / len(v) for v in by_domain.values())
        else:
            out[metric] = sum(values) / len(values)
    return out


def _per_domain(per_item: dict[str, dict[str, float]]) -> dict[str, dict[str, float]]:
    grouped: dict[str, dict[str, list[float]]] = {{}}
    for item_id, metrics in per_item.items():
        domain = PER_SAMPLE_DOMAINS.get(item_id)
        if domain is None:
            continue
        for metric, value in metrics.items():
            grouped.setdefault(domain, {{}}).setdefault(metric, []).append(value)
    return {{d: {{m: sum(v) / len(v) for m, v in ms.items()}} for d, ms in grouped.items()}}


def _apply_gates(agg: dict[str, float], per_domain: dict[str, dict[str, float]]) -> list[str]:
    """Gates are contract DATA (item 2.8) — scope and purpose come from the contract."""
    violations: list[str] = []
    for c in CONSTRAINTS:
        if c["purpose"] != "floor":
            continue  # a goal is a target, not a disqualification
        targets = (
            [(d, m.get(c["metric"])) for d, m in per_domain.items()]
            if c["scope"] == "per_domain"
            else [("all", agg.get(c["metric"]))]
        )
        for where, value in targets:
            if value is None:
                continue
            ok = {{
                ">=": value >= c["threshold"], ">": value > c["threshold"],
                "<=": value <= c["threshold"], "<": value < c["threshold"],
                "==": value == c["threshold"],
            }}.get(c["op"], True)
            if not ok:
                violations.append(f"{{c['metric']}} {{c['op']}} {{c['threshold']}} violated at {{where}} ({{value}})")
    return violations


def main() -> int:
    if len(sys.argv) < 3:
        print(json.dumps({{"error": "usage: evaluate.py <split_dir> <pred_dir>"}}))
        return 2
    split_dir, pred_dir = Path(sys.argv[1]), Path(sys.argv[2])

    gt_items = _load_split(split_dir)
    per_item: dict[str, dict[str, float]] = {{}}
    for item_id, gt in gt_items.items():
        pred_path = pred_dir / item_id
        if not pred_path.exists():
            continue
        per_item[item_id] = score(pred_path.read_bytes(), gt, label_semantics=LABEL_SEMANTICS)

    agg = _aggregate(per_item)
    per_domain = _per_domain(per_item)
    violations = _apply_gates(agg, per_domain)

    print(json.dumps({{
        "metrics": agg,
        "per_domain": per_domain,
        "gate_violations": violations,
        "scored_items": len(per_item),
        "eval_version": {eval_version!r},
        "harness_version": {HARNESS_VERSION},
    }}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def scaffold_evaluator(
    run_dir: Path,
    eval_version: str = "v1",
    *,
    overwrite_plugin: bool = False,
) -> dict[str, Any]:
    """Generate the evaluator harness for a run. Returns a result envelope.

    The score plugin is written ONCE and never overwritten without
    ``overwrite_plugin``: it is the mission's own work, and regenerating the
    harness must not destroy it. The harness itself is always rewritten, because
    being reproducible from declared inputs is the property that makes the seal
    mean something.
    """
    run_dir = Path(run_dir)
    contract_path = run_dir / "goal-contract.json"
    if not contract_path.exists():
        return {"error": f"no goal contract at {contract_path}; the harness is generated from it"}

    try:
        contract = json.loads(contract_path.read_text())
    except Exception as exc:  # noqa: BLE001
        return {"error": f"goal contract is unreadable: {exc}"}

    split_path = run_dir / "frozen-splits" / f"{eval_version}-test.json"
    frozen_split: dict[str, Any] = {}
    if split_path.exists():
        try:
            frozen_split = json.loads(split_path.read_text())
        except Exception:  # noqa: BLE001
            frozen_split = {}

    target_dir = run_dir / "eval-suites"
    target_dir.mkdir(parents=True, exist_ok=True)

    source = _harness_source(
        contract=contract, frozen_split=frozen_split, eval_version=eval_version
    )
    harness_path = target_dir / f"{eval_version}.py"
    harness_path.write_text(source)

    plugin_path = target_dir / SCORE_PLUGIN_FILENAME
    plugin_written = False
    if overwrite_plugin or not plugin_path.exists():
        plugin_path.write_text(
            _PLUGIN_TEMPLATE.format(
                label_semantics=contract.get("label_semantics", "unspecified")
            )
        )
        plugin_written = True

    return {
        "ok": True,
        "harness_path": str(harness_path),
        "plugin_path": str(plugin_path),
        "plugin_written": plugin_written,
        "harness_sha256": hashlib.sha256(source.encode()).hexdigest(),
        "harness_version": HARNESS_VERSION,
        "deterministic": True,
    }


def verify_harness_unmodified(run_dir: Path, eval_version: str = "v1") -> dict[str, Any]:
    """Regenerate and byte-compare — the custody property (item 2.5 / RC1).

    A hand-edited harness is caught here rather than at the seal, where the only
    evidence would be a hash matching a file nobody can reproduce.
    """
    run_dir = Path(run_dir)
    harness_path = run_dir / "eval-suites" / f"{eval_version}.py"
    if not harness_path.exists():
        return {"ok": False, "error": f"no generated harness at {harness_path}"}

    try:
        contract = json.loads((run_dir / "goal-contract.json").read_text())
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "error": f"goal contract is unreadable: {exc}"}

    split_path = run_dir / "frozen-splits" / f"{eval_version}-test.json"
    frozen_split = json.loads(split_path.read_text()) if split_path.exists() else {}

    expected = _harness_source(
        contract=contract, frozen_split=frozen_split, eval_version=eval_version
    )
    actual = harness_path.read_text()
    if expected == actual:
        return {"ok": True, "matches": True}
    return {
        "ok": False,
        "matches": False,
        "error": (
            "the evaluator harness on disk does not match what its declared inputs "
            "generate. Either it was hand-edited — in which case the seal describes a "
            "file nobody can reproduce — or the contract changed without regenerating. "
            "Run evor_scaffold_evaluator to rebuild it."
        ),
    }


def _main(argv: list[str] | None = None) -> int:
    """CLI entry point, so the MCP server can call this as a module."""
    import argparse

    ap = argparse.ArgumentParser(prog="evor.scaffold_evaluator")
    sub = ap.add_subparsers(dest="cmd", required=True)

    gen = sub.add_parser("generate")
    gen.add_argument("--run-dir", required=True)
    gen.add_argument("--eval-version", default="v1")
    gen.add_argument("--overwrite-plugin", action="store_true")

    ver = sub.add_parser("verify")
    ver.add_argument("--run-dir", required=True)
    ver.add_argument("--eval-version", default="v1")

    args = ap.parse_args(argv)
    if args.cmd == "generate":
        result = scaffold_evaluator(
            Path(args.run_dir), args.eval_version, overwrite_plugin=args.overwrite_plugin
        )
    else:
        result = verify_harness_unmodified(Path(args.run_dir), args.eval_version)
    print(json.dumps(result))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(_main())
